# Generated by Django 4.1 on 2022-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
    ]
