# Generated by Django 4.1 on 2022-09-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_isedited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='isEdited',
        ),
    ]
