# Generated by Django 4.1 on 2022-08-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_comments_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
