# Generated by Django 4.1 on 2022-08-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bids_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
